### ISSUE TITLE
Vagrant Up Fails

### ISSUE THREAD

**Issue by kdunn926** [ceph/cephfs-hadoop#21] opened 2015-03-08 07:50 UTC
==> default: [INFO] 6 errors
==> default: [INFO] -------------------------------------------------------------
==> default: [INFO] ------------------------------------------------------------------------
==> default: [INFO] BUILD FAILURE
==> default: [INFO] ------------------------------------------------------------------------
==> default: [INFO]
==> default: Total time: 1:41.463s
==> default: [INFO]
==> default: Finished at: Sun Mar 08 07:46:59 UTC 2015
==> default: [INFO] Final Memory: 22M/52M
==> default: [INFO] ------------------------------------------------------------------------
==> default: [ERROR]
==> default: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project cephfs-hadoop: Compilation failure: Compilation failure:
==> default: [ERROR]
==> default: /ceph-hadoop/src/main/java/org/apache/hadoop/fs/ceph/CephInputStream.java:[46,11] cannot find symbol
==> default: [ERROR]
==> default: symbol  : class CephFS
==> default: [ERROR]
==> default: location: class org.apache.hadoop.fs.ceph.CephInputStream
==> default: [ERROR] /ceph-hadoop/src/main/java/org/apache/hadoop/fs/ceph/CephInputStream.java:[60,46] cannot find symbol
==> default: [ERROR] symbol  : class CephFS
==> default: [ERROR] location: class org.apache.hadoop.fs.ceph.CephInputStream
==> default: [ERROR] /ceph-hadoop/src/main/java/org/apache/hadoop/fs/ceph/CephOutputStream.java:[50,11] cannot find symbol
==> default: [ERROR] symbol  : class CephFS
==> default: [ERROR] location: class org.apache.hadoop.fs.ceph.CephOutputStream
==> default: [ERROR] /ceph-hadoop/src/main/java/org/apache/hadoop/fs/ceph/CephOutputStream.java:[62,47] cannot find symbol
==> default: [ERROR] symbol  : class CephFS
==> default: [ERROR] location: class org.apache.hadoop.fs.ceph.CephOutputStream
==> default: [ERROR] /ceph-hadoop/src/main/java/org/apache/hadoop/fs/ceph/CephTalker.java:[43,26] cannot find symbol
==> default: [ERROR] symbol: class CephFS
==> default: [ERROR] /ceph-hadoop/src/main/java/org/apache/hadoop/fs/ceph/CephFileSystem.java:[71,11] cannot find symbol
==> default: [ERROR] symbol  : class CephFS
==> default: [ERROR] location: class org.apache.hadoop.fs.ceph.CephFileSystem

**Comment by kdunn926** [comment] 2015-03-09 05:56
I am using an OSX host for Vagrant. The problem seems to be related to the files CephFS.java and CephFs.java. I renamed CephFS.java to CephFsProto.java and updated the class references throughout and it compiled fine.

**Comment by noahdesu** [comment] 2015-03-09 15:33
@kdunn926  Are you compiling on HFS+? That file system is not case-sensitive, which might be the cause of the problem. Can you submit a pull request with your fix?

**Comment by kdunn926** [comment] 2015-03-10 16:55
@noahdesu As it turns out, renaming the CephFS.java file to CephFsProto.java was sufficient. I'm not a Java dev so I'm not sure if convention prefers class names be reflected in the file name. If so, I can submit a pull request with the changes I previously described.

**Comment by noahdesu** [comment] 2015-03-10 17:55
@kdunn926 The case sensitivity of HFS+ definitely seems to be the issue. I would have expected Java to complain that the filename didn't match the class name inside. It's probably a good idea to change the class name inside as well. If it wasn't complaining then its probably because Java wasn't trying to load that class.

Can you open a pull request with what you have? I'll do some poking around and see if that code is even being used. I'm gonna reopen this ticket.

**Comment by kdunn926** [comment] 2015-03-12 04:17
@noahdesu Pull request opened. Is this code still relevant or has HDFS drop-in functionality been moved elsewhere in Ceph or dropped altogether?

**Comment by noahdesu** [comment] 2015-03-16 17:52
Thanks for the PR. HDFS drop-in is here and definitely relevant :)  I'll get this merged soon.

**Closed** 2015-11-29 07:01 UTC
